### ISSUE TITLE
Error: Cannot find module '/**/1268' on startup

### ISSUE THREAD

**Issue by yanniz0r** [patternplate/patternplate#190]
Hello!

I'm using the version 2.0.0-84 and followed along your getting started guide. I ran into the following errors:
```
module.js:545
    throw err;
    ^

Error: Cannot find module '/***/my-patternplate/1268'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
module.js:545
    throw err;
    ^

Error: Cannot find module '/***/my-patternplate/1268'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
npm cache clean -f
```
Those errors also occurred with examples from this repository. I tested out the webpack-less and styled-components examples. Besides those error messages, the demos of my components wont render.

I tried it first with the Node version `8.1.0` then I updated to `9.8.0` on MacOS. My npm version is `5.6.0`. I reproduced this error on another machine too.

Thanks in advance,
Yannic

**Comment by marionebl** [comment]
Thanks for reporting, I'll try to reprduce asap.

**Comment by marionebl** [comment]
Reproduced this, working on a fix.

**Comment by marionebl** [comment]
**TL;WR:**

A regression introduced with 4f165f660bb8754938b5968c97b050c1c80ab306. Fix vedfsion is 2.0.0-85. Could you verify this works for you now? Thank you!

–––
Ok, this went down this way: 

In 4f165f660bb8754938b5968c97b050c1c80ab306 I introduced webpack worker processes to protect the main thread against the CPU blocking phases in webpack's lifecycle. 

This employed a combination of `child_process.fork` and `require.resolve`. This works just fine in development mode. The catch here is: To mitigate download times (with limited success) we bundle `@patternplate/cli` for Node.js consumption. 

This effectively breaks `require.resolve`, thus the issue you ran into.

I handle this by creating the worker file on the fly now and use the `BUNDLE` env var already in place for similiar cases to distinguish between bundled and unbundled mode.

**Comment by yanniz0r** [comment]
Hey! Thanks for the fast fix. Works perfectly for me!
